import {
  Patient,
  ClinicalRecord,
  Appointment,
  MedicalRoom,
  DocumentItem,
  ConsentForm,
  InvoiceSIN,
  WhatsAppNotification,
  HealthCampaign,
  CIE10Item,
} from './types';

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'PAT-001',
    name: 'Alejandro Morales Quiroga',
    ci: '4892104 LP',
    age: 42,
    gender: 'M',
    birthDate: '1984-05-14',
    bloodType: 'O+',
    allergies: ['Penicilina', 'Sulfamidas'],
    chronicConditions: ['Hipertensión Arterial Grado 1'],
    phone: '+591 76543210',
    email: 'a.morales@correo.bo',
    emergencyContact: {
      name: 'Carla Quiroga (Esposa)',
      relationship: 'Esposa',
      phone: '+591 77123456',
    },
    insurance: 'Seguro Privado Bisa Salud (Póliza #88392)',
    lastVisit: '2026-08-18',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'PAT-002',
    name: 'Valeria Torrico Camacho',
    ci: '6129845 SC',
    age: 29,
    gender: 'F',
    birthDate: '1997-11-03',
    bloodType: 'A+',
    allergies: ['AINES (Ibuprofeno)', 'Mariscos'],
    chronicConditions: ['Asma bronquial leve intermitente'],
    phone: '+591 71239845',
    email: 'valeria.torrico@gmail.com',
    emergencyContact: {
      name: 'Mario Torrico (Padre)',
      relationship: 'Padre',
      phone: '+591 72345678',
    },
    insurance: 'Particular / Privado',
    lastVisit: '2026-08-10',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'PAT-003',
    name: 'Gonzalo Vacaflor Ríos',
    ci: '3720194 CB',
    age: 58,
    gender: 'M',
    birthDate: '1968-02-21',
    bloodType: 'B+',
    allergies: ['Sin alergias conocidas'],
    chronicConditions: ['Diabetes Mellitus Tipo 2', 'Dislipidemia'],
    phone: '+591 70192834',
    email: 'gonzalo.vacaflor@entel.bo',
    emergencyContact: {
      name: 'Sonia Ríos (Hermana)',
      relationship: 'Hermana',
      phone: '+591 78901234',
    },
    insurance: 'Caja Nacional de Salud (Derivado)',
    lastVisit: '2026-07-29',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'PAT-004',
    name: 'Luciana Mendizábal Flores',
    ci: '8934521 LP',
    age: 34,
    gender: 'F',
    birthDate: '1992-09-17',
    bloodType: 'AB+',
    allergies: ['Látex'],
    chronicConditions: ['Gastritis Crónica'],
    phone: '+591 77890123',
    email: 'luciana.mendizabal@live.com',
    emergencyContact: {
      name: 'Diego Flores (Esposo)',
      relationship: 'Esposo',
      phone: '+591 75432109',
    },
    insurance: 'Alianza Seguros Salud #4421',
    lastVisit: '2026-08-22',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'PAT-005',
    name: 'Roberto Daza Benavides',
    ci: '5391203 TJ',
    age: 63,
    gender: 'M',
    birthDate: '1963-04-12',
    bloodType: 'O-',
    allergies: ['Dipirona (Metamizol)'],
    chronicConditions: ['Colelitiasis Sintomática', 'Cardiopatía Isquémica Controlada'],
    phone: '+591 72109876',
    email: 'roberto.daza@tarija.bo',
    emergencyContact: {
      name: 'Elena Daza (Hija)',
      relationship: 'Hija',
      phone: '+591 79876543',
    },
    insurance: 'Seguro Privado Nacional Seguros',
    lastVisit: '2026-08-24',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
];

export const CIE10_DATABASE: CIE10Item[] = [
  { code: 'I10', description: 'Hipertensión esencial (primaria)', category: 'Cardiovascular' },
  { code: 'E11.9', description: 'Diabetes mellitus tipo 2 sin complicaciones', category: 'Endocrino' },
  { code: 'K29.7', description: 'Gastritis, no especificada', category: 'Gastroenterología' },
  { code: 'K80.2', description: 'Cálculo de la vesícula biliar sin colecistitis (Colelitiasis)', category: 'Gastroenterología' },
  { code: 'J00', description: 'Rinofaringitis aguda (resfriado común)', category: 'Respiratorio' },
  { code: 'J03.9', description: 'Amigdalitis aguda, no especificada', category: 'Respiratorio' },
  { code: 'J45.0', description: 'Asma predominantemente alérgica', category: 'Respiratorio' },
  { code: 'K35.8', description: 'Apendicitis aguda no especificada', category: 'Cirugía General' },
  { code: 'M54.5', description: 'Lumbago no especificado / Lumbalgia', category: 'Traumatología' },
  { code: 'N39.0', description: 'Infección de vías urinarias, sitio no especificado', category: 'Urología' },
  { code: 'A09.0', description: 'Gastroenteritis y colitis de origen infeccioso', category: 'Infectología' },
  { code: 'R10.4', description: 'Dolor abdominal no especificado y otros dolores abdominales', category: 'Síntomas Generales' },
  { code: 'R51', description: 'Cefalea / Dolor de cabeza tensional', category: 'Neurología' },
  { code: 'E66.9', description: 'Obesidad, no especificada', category: 'Nutrición / Metabólico' },
  { code: 'Z00.0', description: 'Examen médico general de rutina (Chequeo preventivo)', category: 'Medicina Preventiva' },
];

export const INITIAL_CLINICAL_RECORDS: ClinicalRecord[] = [
  {
    id: 'REC-2026-089',
    patientId: 'PAT-001',
    date: '2026-08-18 10:30',
    doctor: 'Dr. Carlos Mendoza (Cirugía / Med. General)',
    specialty: 'Medicina General y Preventiva',
    reason: 'Control rutinario de presión arterial y dolor precordial leve tras esfuerzo.',
    anamnesis: 'Paciente refiere cefalea matutina occipital ocasional y sensación de fatiga. Buen apego a la dieta hiposódica en días laborales.',
    vitals: {
      bp: '135/85',
      hr: 76,
      temp: 36.5,
      spo2: 98,
      weight: 78.5,
      height: 176,
      bmi: 25.3,
    },
    physicalExam: 'Paciente consciente, orientado en tiempo y espacio. Ruidos cardíacos rítmicos normofonéticos sin soplos. Campos pulmonares bien ventilados. Abdomen blando, depresible, no doloroso.',
    cie10Code: 'I10',
    cie10Desc: 'Hipertensión esencial (primaria)',
    prescription: [
      {
        id: 'rx-1',
        medication: 'Losartán Potásico 50 mg',
        dosage: '1 comprimido vía oral',
        frequency: 'Cada 24 horas (mañana)',
        duration: '30 días',
        notes: 'Tomar con el desayuno.',
      },
      {
        id: 'rx-2',
        medication: 'Ácido Acetilsalicílico (Cardioaspirina) 100 mg',
        dosage: '1 comprimido vía oral',
        frequency: 'Cada 24 horas (después del almuerzo)',
        duration: '30 días',
        notes: 'Protección cardiovascular preventiva.',
      },
    ],
    treatmentPlan: 'Continuar régimen farmacológico. Ejercicio aeróbico moderado 30 min 4 veces por semana. Registro diario de PA por 7 días.',
    requiresFollowUp: true,
    followUpDate: '2026-09-18',
  },
  {
    id: 'REC-2026-045',
    patientId: 'PAT-001',
    date: '2026-05-12 16:15',
    doctor: 'Dra. Marcela Ugarte (Cardiología)',
    specialty: 'Cardiología',
    reason: 'Evaluación cardiológica anual y electrocardiograma basal.',
    anamnesis: 'Paciente asintomático cardiovascular agudo. Niega síncope o disnea paroxística nocturna.',
    vitals: {
      bp: '130/80',
      hr: 72,
      temp: 36.4,
      spo2: 99,
      weight: 79.0,
      height: 176,
      bmi: 25.5,
    },
    physicalExam: 'ECG muestra ritmo sinusal, FC 72 lpm, sin signos de isquemia subepicárdica ni hipertrofia ventricular izquierda.',
    cie10Code: 'I10',
    cie10Desc: 'Hipertensión esencial (primaria)',
    prescription: [
      {
        id: 'rx-3',
        medication: 'Losartán Potásico 50 mg',
        dosage: '1 comprimido',
        frequency: 'Cada 24 horas',
        duration: '90 días',
      },
    ],
    treatmentPlan: 'Control en 3 meses con perfil lipídico y química sanguínea.',
    requiresFollowUp: true,
    followUpDate: '2026-08-18',
  },
  {
    id: 'REC-2026-077',
    patientId: 'PAT-005',
    date: '2026-08-24 09:00',
    doctor: 'Dr. Carlos Mendoza (Cirugía General)',
    specialty: 'Cirugía General / Quirúrgica',
    reason: 'Evaluación prequirúrgica por cólicos biliares a repetición.',
    anamnesis: 'Paciente con diagnóstico ecográfico de litiasis vesicular múltiple. Cuadros recurrentes postprandiales grasos. Se decide programar Colecistectomía Laparoscópica.',
    vitals: {
      bp: '125/80',
      hr: 70,
      temp: 36.7,
      spo2: 97,
      weight: 84.0,
      height: 172,
      bmi: 28.4,
    },
    physicalExam: 'Abdomen blando, dolor leve en hipocondrio derecho a la palpación profunda. Signo de Murphy negativo en el momento.',
    cie10Code: 'K80.2',
    cie10Desc: 'Cálculo de la vesícula biliar sin colecistitis (Colelitiasis)',
    prescription: [
      {
        id: 'rx-4',
        medication: 'Hioscina N-Butilbromuro + Paracetamol',
        dosage: '1 comprimido en caso de dolor espasmódico',
        frequency: 'Condicional al dolor (máx cada 8h)',
        duration: '5 días',
      },
    ],
    treatmentPlan: 'Programación quirúrgica en Quirófano 1. Firma de consentimiento informado y valoración anestesiológica previa.',
    requiresFollowUp: true,
    followUpDate: '2026-08-26',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'APT-101',
    patientId: 'PAT-005',
    patientName: 'Roberto Daza Benavides',
    patientCi: '5391203 TJ',
    patientPhone: '+591 72109876',
    doctorName: 'Dr. Carlos Mendoza',
    specialty: 'Cirugía General',
    date: '2026-08-26',
    time: '08:30',
    durationMin: 90,
    type: 'Cirugía Programada',
    room: 'Quirófano Central 01',
    status: 'Confirmada',
    notes: 'Colecistectomía laparoscópica. Paciente en ayunas desde las 22:00 previo.',
  },
  {
    id: 'APT-102',
    patientId: 'PAT-001',
    patientName: 'Alejandro Morales Quiroga',
    patientCi: '4892104 LP',
    patientPhone: '+591 76543210',
    doctorName: 'Dr. Carlos Mendoza',
    specialty: 'Medicina General',
    date: '2026-08-25',
    time: '10:00',
    durationMin: 30,
    type: 'Control Post-Operatorio',
    room: 'Consultorio 204',
    status: 'Confirmada',
    notes: 'Revisión de mapa de presión arterial y ajuste de dosis.',
  },
  {
    id: 'APT-103',
    patientId: 'PAT-002',
    patientName: 'Valeria Torrico Camacho',
    patientCi: '6129845 SC',
    patientPhone: '+591 71239845',
    doctorName: 'Dra. Andrea Salguero',
    specialty: 'Ginecología y Obstetricia',
    date: '2026-08-25',
    time: '11:15',
    durationMin: 45,
    type: 'Consulta General',
    room: 'Consultorio 102',
    status: 'Pendiente',
    notes: 'Chequeo ecográfico pélvico anual.',
  },
  {
    id: 'APT-104',
    patientId: 'PAT-004',
    patientName: 'Luciana Mendizábal Flores',
    patientCi: '8934521 LP',
    patientPhone: '+591 77890123',
    doctorName: 'Dr. Roberto Siles',
    specialty: 'Gastroenterología',
    date: '2026-08-25',
    time: '15:00',
    durationMin: 40,
    type: 'Procedimiento Menor',
    room: 'Tópico Endoscopía A',
    status: 'Confirmada',
    notes: 'Endoscopía digestiva alta diagnóstica con biopsia.',
  },
  {
    id: 'APT-105',
    patientId: 'PAT-003',
    patientName: 'Gonzalo Vacaflor Ríos',
    patientCi: '3720194 CB',
    patientPhone: '+591 70192834',
    doctorName: 'Dr. Carlos Mendoza',
    specialty: 'Medicina Interna',
    date: '2026-08-27',
    time: '09:00',
    durationMin: 30,
    type: 'Especialidad',
    room: 'Consultorio 204',
    status: 'Pendiente',
    notes: 'Revisión de hemoglobina glicosilada HbA1c y fondo de ojo.',
  },
];

export const INITIAL_ROOMS: MedicalRoom[] = [
  {
    id: 'ROOM-Q1',
    name: 'Quirófano Central 01',
    type: 'Quirófano',
    status: 'En Cirugía',
    currentPatient: 'Mariana Zalles Rocha',
    currentDoctor: 'Dr. Carlos Mendoza',
    currentProcedure: 'Hernioplastia Inguinal con Malla',
    endTime: '11:45 AM',
    equipment: ['Torre Laparoscópica Stryker 4K', 'Máquina de Anestesia Dräger', 'Electrobisturí Valleylab', 'Monitor Multiparamétrico'],
  },
  {
    id: 'ROOM-Q2',
    name: 'Quirófano 02 (Traumatología y Ortopedia)',
    type: 'Quirófano',
    status: 'Disponible',
    endTime: 'Listo para programar',
    equipment: ['Arco en C Siemens Fluoroscopía', 'Mesa Radiotransparente', 'Set Instrumental Ortopedia'],
  },
  {
    id: 'ROOM-C204',
    name: 'Consultorio 204 (Medicina / Cirugía)',
    type: 'Consultorio',
    status: 'En Consulta',
    currentPatient: 'Alejandro Morales Quiroga',
    currentDoctor: 'Dr. Carlos Mendoza',
    currentProcedure: 'Consulta Médica Externa',
    endTime: '10:30 AM',
    equipment: ['Camilla de Exploración', 'Negatoscopio LED', 'Dermatoscopio', 'Tensiómetro Welch Allyn'],
  },
  {
    id: 'ROOM-C102',
    name: 'Consultorio 102 (Ginecología / Ecografía)',
    type: 'Consultorio',
    status: 'Disponible',
    endTime: 'Próxima cita 11:15 AM',
    equipment: ['Ecógrafo Voluson E8 HD Live', 'Camilla Ginecológica Eléctrica', 'Colposcopio'],
  },
  {
    id: 'ROOM-TOP1',
    name: 'Tópico Endoscopía y Procedimientos',
    type: 'Tópico Procedimientos',
    status: 'Mantenimiento / Limpieza',
    endTime: 'Desinfección de alto nivel hasta 14:00',
    equipment: ['Torre Olympus Exera III', 'Reprocesador Automático de Endoscopios', 'Oximetría continua'],
  },
  {
    id: 'ROOM-REC1',
    name: 'Sala de Recuperación Post-Anestésica (URPA)',
    type: 'Sala Recuperación',
    status: 'Disponible',
    currentPatient: '2 Camas ocupadas de 6 totales',
    endTime: 'Capacidad 67% disponible',
    equipment: ['Monitores de Saturación Central', 'Tomas de O2 y Aspiración por cama', 'Carro de Paro con Desfibrilador'],
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'DOC-501',
    patientId: 'PAT-001',
    patientName: 'Alejandro Morales Quiroga',
    patientCi: '4892104 LP',
    title: 'Informe Electrocardiograma 12 Derivaciones',
    category: 'Informe Quirúrgico',
    date: '2026-08-18',
    doctor: 'Dra. Marcela Ugarte',
    fileType: 'PDF',
    fileSize: '1.4 MB',
    isSigned: true,
    signatureHash: 'SHA256: 8f4a2b91c0e39478f1d3e809b4',
    previewUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'DOC-502',
    patientId: 'PAT-005',
    patientName: 'Roberto Daza Benavides',
    patientCi: '5391203 TJ',
    title: 'Consentimiento Informado Colecistectomía Laparoscópica',
    category: 'Consentimiento',
    date: '2026-08-24',
    doctor: 'Dr. Carlos Mendoza',
    fileType: 'PDF Firmado',
    fileSize: '840 KB',
    isSigned: true,
    signatureHash: 'SHA256: 4b29a8f117c09348e02d8f9a2b',
    previewUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'DOC-503',
    patientId: 'PAT-001',
    patientName: 'Alejandro Morales Quiroga',
    patientCi: '4892104 LP',
    title: 'Laboratorio Perfil Lipídico y Química Sanguínea',
    category: 'Laboratorio',
    date: '2026-08-15',
    doctor: 'Bioq. Claudia Zeballos',
    fileType: 'PDF',
    fileSize: '520 KB',
    isSigned: true,
    signatureHash: 'SHA256: 9e1028fa723bc410984daef021',
  },
  {
    id: 'DOC-504',
    patientId: 'PAT-005',
    patientName: 'Roberto Daza Benavides',
    patientCi: '5391203 TJ',
    title: 'Ecografía Abdominal Total (Vesícula Biliar)',
    category: 'Ecografía',
    date: '2026-08-20',
    doctor: 'Dr. Javier Villarroel (Imagenología)',
    fileType: 'PDF / DICOM',
    fileSize: '4.8 MB',
    isSigned: true,
    signatureHash: 'SHA256: 71a9f0482bd940381ec8094a12',
  },
  {
    id: 'DOC-505',
    patientId: 'PAT-004',
    patientName: 'Luciana Mendizábal Flores',
    patientCi: '8934521 LP',
    title: 'Radiografía de Tórax PA y Lateral Digital',
    category: 'Radiología',
    date: '2026-08-22',
    doctor: 'Dr. Javier Villarroel',
    fileType: 'DICOM / PDF',
    fileSize: '6.2 MB',
    isSigned: true,
    signatureHash: 'SHA256: d840192eab7394850123984fab',
  },
];

export const INITIAL_CONSENT_FORM: ConsentForm = {
  id: 'CONF-2026-01',
  patientId: 'PAT-005',
  patientName: 'Roberto Daza Benavides',
  patientCi: '5391203 TJ',
  procedureName: 'Colecistectomía Laparoscópica + Exploración de Vía Biliar',
  department: 'Servicio de Cirugía General y Digestiva',
  risksText: 'Comprendo que el procedimiento quirúrgico consiste en la extirpación de la vesícula biliar mediante técnica mini-invasiva video-laparoscópica. He sido informado de los riesgos habituales que incluyen: sangrado, infección del sitio quirúrgico, lesión de conductos biliares o vísceras adyacentes, fuga biliar, necesidad de conversión a cirugía abierta convencional si las condiciones anatómicas lo ameritan, y riesgos anestesiológicos generales. Declaro haber tenido la oportunidad de formular todas las preguntas y que las mismas han sido respondidas a mi entera satisfacción.',
  doctorName: 'Dr. Carlos Mendoza - Matrícula Profesional Med. #7492-LP',
  signedDate: '2026-08-24 11:20',
  status: 'Firmado Electrónicamente',
  hash: 'SHA256-MEDSYS-8930492817492019485720194857392019485',
};

export const INITIAL_INVOICES: InvoiceSIN[] = [
  {
    id: 'INV-2026-00481',
    invoiceNumber: '00481',
    authorizationNumber: '4910293849102',
    cuf: '8FA92B019284716294029485720193847562019485729104',
    nitEmisor: '3829102019',
    razonSocialEmisor: 'CLÍNICA ESPECIALIZADA MEDICALSYS S.R.L.',
    nitCiCliente: '4892104',
    complemento: 'LP',
    razonSocialCliente: 'Alejandro Morales Quiroga',
    emailCliente: 'a.morales@correo.bo',
    fechaEmision: '2026-08-24 10:45:12',
    paymentMethod: 'QR Simple',
    items: [
      {
        id: 'item-1',
        code: 'MED-SER-01',
        description: 'Consulta Médica con Especialista (Cirugía / Med. Interna)',
        quantity: 1,
        unitPrice: 250,
        subtotal: 250,
      },
      {
        id: 'item-2',
        code: 'MED-LAB-04',
        description: 'Electrocardiograma Digital con Informe Médico',
        quantity: 1,
        unitPrice: 120,
        subtotal: 120,
      },
    ],
    subtotal: 370,
    discount: 0,
    total: 370,
    qrData: 'https://siat.sin.gob.bo/consulta/QR?nit=3829102019&cuf=8FA92B019284716294029485720193847562019485729104&numero=00481&monto=370.00&fecha=24/08/2026',
    status: 'Válida',
    cashier: 'Lic. Mariana Velasco (Caja Central)',
  },
  {
    id: 'INV-2026-00480',
    invoiceNumber: '00480',
    authorizationNumber: '4910293849102',
    cuf: '7EA81C091837462819203948571029384756102938471829',
    nitEmisor: '3829102019',
    razonSocialEmisor: 'CLÍNICA ESPECIALIZADA MEDICALSYS S.R.L.',
    nitCiCliente: '8934521',
    complemento: 'LP',
    razonSocialCliente: 'Luciana Mendizábal Flores',
    emailCliente: 'luciana.mendizabal@live.com',
    fechaEmision: '2026-08-23 16:20:00',
    paymentMethod: 'Tarjeta de Débito/Crédito',
    items: [
      {
        id: 'item-3',
        code: 'MED-IMG-02',
        description: 'Radiografía Digital de Tórax (2 Incidencias PA y Lateral)',
        quantity: 1,
        unitPrice: 180,
        subtotal: 180,
      },
    ],
    subtotal: 180,
    discount: 0,
    total: 180,
    qrData: 'https://siat.sin.gob.bo/consulta/QR?nit=3829102019&cuf=7EA81C091837462819203948571029384756102938471829&numero=00480&monto=180.00&fecha=23/08/2026',
    status: 'Válida',
    cashier: 'Lic. Mariana Velasco',
  },
];

export const INITIAL_NOTIFICATIONS: WhatsAppNotification[] = [
  {
    id: 'WA-001',
    patientName: 'Roberto Daza Benavides',
    phone: '+591 72109876',
    type: 'Confirmación de Cita',
    message: '🏥 *MedicalSys Clínica:* Estimado(a) Roberto Daza, confirmamos su cita quirúrgica programada para el miércoles 26 de Agosto a las 08:30 con el Dr. Carlos Mendoza en Quirófano Central 01. Recuerde 8 horas de ayuno. Responda SI para reconfirmar.',
    timestamp: 'Hoy a las 11:25 AM',
    status: 'Respondido',
  },
  {
    id: 'WA-002',
    patientName: 'Alejandro Morales Quiroga',
    phone: '+591 76543210',
    type: 'Receta Digital',
    message: '📋 *MedicalSys:* Hola Alejandro Morales, su receta médica digital de la consulta de hoy ha sido generada con éxito. Puede presentarla en farmacia o descargarla en el siguiente enlace seguro: https://medsys.app/rx/rec-2026-089',
    timestamp: 'Hoy a las 10:48 AM',
    status: 'Leído',
  },
  {
    id: 'WA-003',
    patientName: 'Luciana Mendizábal Flores',
    phone: '+591 77890123',
    type: 'Recordatorio 24h',
    message: '⏰ *Recordatorio MedicalSys:* Hola Luciana, le recordamos su procedimiento endoscópico mañana 25 de Agosto a las 15:00 en Tópico Endoscopía A con el Dr. Roberto Siles. Por favor asistir 15 min antes con un acompañante.',
    timestamp: 'Hoy a las 09:15 AM',
    status: 'Entregado',
  },
  {
    id: 'WA-004',
    patientName: 'Valeria Torrico Camacho',
    phone: '+591 71239845',
    type: 'Resultados Listos',
    message: '🔬 *Resultados Listos:* Estimada Valeria, sus análisis de laboratorio ya se encuentran disponibles en su portal del paciente. Todo el equipo médico está a su disposición.',
    timestamp: 'Ayer a las 18:30 PM',
    status: 'Leído',
  },
];

export const INITIAL_CAMPAIGNS: HealthCampaign[] = [
  {
    id: 'CAMP-01',
    name: 'Jornada Preventiva de Salud Cardiovascular & Hipertensión',
    targetAudience: 'Pacientes mayores de 40 años o con diagnóstico de Hipertensión',
    recipientCount: 148,
    messageTemplate: '🩺 *MedicalSys Salud:* ¡Cuida tu corazón! Durante este mes accede a un 25% de descuento en Chequeo Cardiológico Completo (Electrocardiograma + Consulta Especializada + Perfil Lipídico). Agenda tu espacio aquí.',
    discountOrBenefit: '25% Descuento en Chequeo Cardiovascular',
    sentDate: '2026-08-20',
    status: 'Enviada',
    readRate: '92.4%',
    bookedCount: 38,
  },
  {
    id: 'CAMP-02',
    name: 'Campaña Detección Temprana y Control de Diabetes',
    targetAudience: 'Pacientes con antecedentes metabólicos / diabetes',
    recipientCount: 95,
    messageTemplate: '🩸 *Control Médico MedicalSys:* Mantén tus niveles bajo control. Realiza tu prueba de Hemoglobina Glicosilada HbA1c + Evaluación Nutricional con tarifa preferencial.',
    discountOrBenefit: 'Paquete Laboratorio + Nutrición Bs. 150',
    sentDate: '2026-08-12',
    status: 'Enviada',
    readRate: '88.5%',
    bookedCount: 26,
  },
];
